/*
 * generated by Xtext 2.10.0
 */
package org.refactor.validation

import org.eclipse.xtext.validation.Check
import org.refactor.modelEditor.Class
import org.refactor.modelEditor.Method
import org.refactor.modelEditor.ModelEditorPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ModelEditorValidator extends AbstractModelEditorValidator {

	@Check
	def checkFeatureEnvy(Method methodElement) {
		var checker = new FeatureEnvyChecker(methodElement);
		if (checker.check()) {
			warning(checker.getMessage(), ModelEditorPackage.Literals.METHOD__NAME);
		}
	}
	
	@Check
	def checkDataClass(Class classElement) {
		var checker = new DataClassChecker(classElement);
		if (checker.check()) {
			warning(checker.getMessage(), ModelEditorPackage.Literals.CLASS__NAME);
		}
	}
	
//	@Check
//	def checkGodClass(Class classElement) {
//		if (classElement.members.length > 2) {
//			warning('Too complex', ModelEditorPackage.Literals.METHOD__CYCLO);
//		}
//	}
	
}
