/**
 * generated by Xtext 2.10.0
 */
package org.refactor.modelEditor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.refactor.modelEditor.Access#getAccesses <em>Accesses</em>}</li>
 *   <li>{@link org.refactor.modelEditor.Access#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see org.refactor.modelEditor.ModelEditorPackage#getAccess()
 * @model
 * @generated
 */
public interface Access extends EObject
{
  /**
   * Returns the value of the '<em><b>Accesses</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Accesses</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Accesses</em>' attribute.
   * @see #setAccesses(int)
   * @see org.refactor.modelEditor.ModelEditorPackage#getAccess_Accesses()
   * @model
   * @generated
   */
  int getAccesses();

  /**
   * Sets the value of the '{@link org.refactor.modelEditor.Access#getAccesses <em>Accesses</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Accesses</em>' attribute.
   * @see #getAccesses()
   * @generated
   */
  void setAccesses(int value);

  /**
   * Returns the value of the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' reference.
   * @see #setField(Field)
   * @see org.refactor.modelEditor.ModelEditorPackage#getAccess_Field()
   * @model
   * @generated
   */
  Field getField();

  /**
   * Sets the value of the '{@link org.refactor.modelEditor.Access#getField <em>Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' reference.
   * @see #getField()
   * @generated
   */
  void setField(Field value);

} // Access
