/**
 * generated by Xtext 2.10.0
 */
package org.refactor.modelEditor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.refactor.modelEditor.Call#getCalls <em>Calls</em>}</li>
 *   <li>{@link org.refactor.modelEditor.Call#getMethod <em>Method</em>}</li>
 * </ul>
 *
 * @see org.refactor.modelEditor.ModelEditorPackage#getCall()
 * @model
 * @generated
 */
public interface Call extends EObject
{
  /**
   * Returns the value of the '<em><b>Calls</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calls</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calls</em>' attribute.
   * @see #setCalls(int)
   * @see org.refactor.modelEditor.ModelEditorPackage#getCall_Calls()
   * @model
   * @generated
   */
  int getCalls();

  /**
   * Sets the value of the '{@link org.refactor.modelEditor.Call#getCalls <em>Calls</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Calls</em>' attribute.
   * @see #getCalls()
   * @generated
   */
  void setCalls(int value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' reference.
   * @see #setMethod(Method)
   * @see org.refactor.modelEditor.ModelEditorPackage#getCall_Method()
   * @model
   * @generated
   */
  Method getMethod();

  /**
   * Sets the value of the '{@link org.refactor.modelEditor.Call#getMethod <em>Method</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' reference.
   * @see #getMethod()
   * @generated
   */
  void setMethod(Method value);

} // Call
