/**
 * generated by Xtext 2.10.0
 */
package org.refactor.modelEditor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Supertypes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.refactor.modelEditor.Supertypes#getSuperTypes <em>Super Types</em>}</li>
 * </ul>
 *
 * @see org.refactor.modelEditor.ModelEditorPackage#getSupertypes()
 * @model
 * @generated
 */
public interface Supertypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Super Types</b></em>' reference list.
   * The list contents are of type {@link org.refactor.modelEditor.Class}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Super Types</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Types</em>' reference list.
   * @see org.refactor.modelEditor.ModelEditorPackage#getSupertypes_SuperTypes()
   * @model
   * @generated
   */
  EList<org.refactor.modelEditor.Class> getSuperTypes();

} // Supertypes
