/**
 * generated by Xtext 2.10.0
 */
package org.refactor.validation;

import org.eclipse.xtext.validation.Check;
import org.refactor.modelEditor.Method;
import org.refactor.modelEditor.ModelEditorPackage;
import org.refactor.validation.AbstractModelEditorValidator;
import org.refactor.validation.DataClassChecker;
import org.refactor.validation.FeatureEnvyChecker;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModelEditorValidator extends AbstractModelEditorValidator {
  @Check
  public void checkFeatureEnvy(final Method methodElement) {
    FeatureEnvyChecker checker = new FeatureEnvyChecker(methodElement);
    boolean _check = checker.check();
    if (_check) {
      String _message = checker.getMessage();
      this.warning(_message, ModelEditorPackage.Literals.METHOD__NAME);
    }
  }
  
  @Check
  public void checkDataClass(final org.refactor.modelEditor.Class classElement) {
    DataClassChecker checker = new DataClassChecker(classElement);
    boolean _check = checker.check();
    if (_check) {
      String _message = checker.getMessage();
      this.warning(_message, ModelEditorPackage.Literals.CLASS__NAME);
    }
  }
}
