/**
 * generated by Xtext 2.10.0
 */
package org.refactor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.refactor.ui.AbstractModelEditorUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelEditorUiModule extends AbstractModelEditorUiModule {
  public ModelEditorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
