/*
 * generated by Xtext 2.10.0
 */
package org.refactor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ModelEditorRuntimeModule extends AbstractModelEditorRuntimeModule {
}
