/*
 * generated by Xtext 2.10.0
 */
package org.refactor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelEditorStandaloneSetup extends ModelEditorStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelEditorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
