/**
 * generated by Xtext 2.10.0
 */
package org.refactor.modelEditor.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.refactor.modelEditor.Access;
import org.refactor.modelEditor.Call;
import org.refactor.modelEditor.Method;
import org.refactor.modelEditor.ModelEditorPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getModifier <em>Modifier</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getTypes <em>Types</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getLoc <em>Loc</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getCyclo <em>Cyclo</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getAccesses <em>Accesses</em>}</li>
 *   <li>{@link org.refactor.modelEditor.impl.MethodImpl#getCalls <em>Calls</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MethodImpl extends MinimalEObjectImpl.Container implements Method
{
  /**
   * The default value of the '{@link #getModifier() <em>Modifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModifier()
   * @generated
   * @ordered
   */
  protected static final String MODIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModifier() <em>Modifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModifier()
   * @generated
   * @ordered
   */
  protected String modifier = MODIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypes() <em>Types</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypes()
   * @generated
   * @ordered
   */
  protected EList<org.refactor.modelEditor.Class> types;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected org.refactor.modelEditor.Class type;

  /**
   * The default value of the '{@link #getLoc() <em>Loc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoc()
   * @generated
   * @ordered
   */
  protected static final int LOC_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLoc() <em>Loc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoc()
   * @generated
   * @ordered
   */
  protected int loc = LOC_EDEFAULT;

  /**
   * The default value of the '{@link #getCyclo() <em>Cyclo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCyclo()
   * @generated
   * @ordered
   */
  protected static final int CYCLO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCyclo() <em>Cyclo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCyclo()
   * @generated
   * @ordered
   */
  protected int cyclo = CYCLO_EDEFAULT;

  /**
   * The cached value of the '{@link #getAccesses() <em>Accesses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccesses()
   * @generated
   * @ordered
   */
  protected EList<Access> accesses;

  /**
   * The cached value of the '{@link #getCalls() <em>Calls</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalls()
   * @generated
   * @ordered
   */
  protected EList<Call> calls;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelEditorPackage.Literals.METHOD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getModifier()
  {
    return modifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setModifier(String newModifier)
  {
    String oldModifier = modifier;
    modifier = newModifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelEditorPackage.METHOD__MODIFIER, oldModifier, modifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelEditorPackage.METHOD__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<org.refactor.modelEditor.Class> getTypes()
  {
    if (types == null)
    {
      types = new EObjectResolvingEList<org.refactor.modelEditor.Class>(org.refactor.modelEditor.Class.class, this, ModelEditorPackage.METHOD__TYPES);
    }
    return types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.refactor.modelEditor.Class getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (org.refactor.modelEditor.Class)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ModelEditorPackage.METHOD__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.refactor.modelEditor.Class basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(org.refactor.modelEditor.Class newType)
  {
    org.refactor.modelEditor.Class oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelEditorPackage.METHOD__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLoc()
  {
    return loc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLoc(int newLoc)
  {
    int oldLoc = loc;
    loc = newLoc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelEditorPackage.METHOD__LOC, oldLoc, loc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getCyclo()
  {
    return cyclo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCyclo(int newCyclo)
  {
    int oldCyclo = cyclo;
    cyclo = newCyclo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelEditorPackage.METHOD__CYCLO, oldCyclo, cyclo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Access> getAccesses()
  {
    if (accesses == null)
    {
      accesses = new EObjectContainmentEList<Access>(Access.class, this, ModelEditorPackage.METHOD__ACCESSES);
    }
    return accesses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Call> getCalls()
  {
    if (calls == null)
    {
      calls = new EObjectContainmentEList<Call>(Call.class, this, ModelEditorPackage.METHOD__CALLS);
    }
    return calls;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ModelEditorPackage.METHOD__ACCESSES:
        return ((InternalEList<?>)getAccesses()).basicRemove(otherEnd, msgs);
      case ModelEditorPackage.METHOD__CALLS:
        return ((InternalEList<?>)getCalls()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ModelEditorPackage.METHOD__MODIFIER:
        return getModifier();
      case ModelEditorPackage.METHOD__NAME:
        return getName();
      case ModelEditorPackage.METHOD__TYPES:
        return getTypes();
      case ModelEditorPackage.METHOD__TYPE:
        if (resolve) return getType();
        return basicGetType();
      case ModelEditorPackage.METHOD__LOC:
        return getLoc();
      case ModelEditorPackage.METHOD__CYCLO:
        return getCyclo();
      case ModelEditorPackage.METHOD__ACCESSES:
        return getAccesses();
      case ModelEditorPackage.METHOD__CALLS:
        return getCalls();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ModelEditorPackage.METHOD__MODIFIER:
        setModifier((String)newValue);
        return;
      case ModelEditorPackage.METHOD__NAME:
        setName((String)newValue);
        return;
      case ModelEditorPackage.METHOD__TYPES:
        getTypes().clear();
        getTypes().addAll((Collection<? extends org.refactor.modelEditor.Class>)newValue);
        return;
      case ModelEditorPackage.METHOD__TYPE:
        setType((org.refactor.modelEditor.Class)newValue);
        return;
      case ModelEditorPackage.METHOD__LOC:
        setLoc((Integer)newValue);
        return;
      case ModelEditorPackage.METHOD__CYCLO:
        setCyclo((Integer)newValue);
        return;
      case ModelEditorPackage.METHOD__ACCESSES:
        getAccesses().clear();
        getAccesses().addAll((Collection<? extends Access>)newValue);
        return;
      case ModelEditorPackage.METHOD__CALLS:
        getCalls().clear();
        getCalls().addAll((Collection<? extends Call>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ModelEditorPackage.METHOD__MODIFIER:
        setModifier(MODIFIER_EDEFAULT);
        return;
      case ModelEditorPackage.METHOD__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ModelEditorPackage.METHOD__TYPES:
        getTypes().clear();
        return;
      case ModelEditorPackage.METHOD__TYPE:
        setType((org.refactor.modelEditor.Class)null);
        return;
      case ModelEditorPackage.METHOD__LOC:
        setLoc(LOC_EDEFAULT);
        return;
      case ModelEditorPackage.METHOD__CYCLO:
        setCyclo(CYCLO_EDEFAULT);
        return;
      case ModelEditorPackage.METHOD__ACCESSES:
        getAccesses().clear();
        return;
      case ModelEditorPackage.METHOD__CALLS:
        getCalls().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ModelEditorPackage.METHOD__MODIFIER:
        return MODIFIER_EDEFAULT == null ? modifier != null : !MODIFIER_EDEFAULT.equals(modifier);
      case ModelEditorPackage.METHOD__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ModelEditorPackage.METHOD__TYPES:
        return types != null && !types.isEmpty();
      case ModelEditorPackage.METHOD__TYPE:
        return type != null;
      case ModelEditorPackage.METHOD__LOC:
        return loc != LOC_EDEFAULT;
      case ModelEditorPackage.METHOD__CYCLO:
        return cyclo != CYCLO_EDEFAULT;
      case ModelEditorPackage.METHOD__ACCESSES:
        return accesses != null && !accesses.isEmpty();
      case ModelEditorPackage.METHOD__CALLS:
        return calls != null && !calls.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (modifier: ");
    result.append(modifier);
    result.append(", name: ");
    result.append(name);
    result.append(", loc: ");
    result.append(loc);
    result.append(", cyclo: ");
    result.append(cyclo);
    result.append(')');
    return result.toString();
  }

} //MethodImpl
