/*
 * generated by Xtext 2.10.0
 */
package org.refactor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModelEditorScopeProvider extends DelegatingScopeProvider {
}
