/*
 * generated by Xtext 2.10.0
 */
package org.refactor.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import reFactor.ui.internal.ReFactorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelEditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ReFactorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ReFactorActivator.getInstance().getInjector(ReFactorActivator.ORG_REFACTOR_MODELEDITOR);
	}
	
}
