/**
 * generated by Xtext 2.10.0
 */
package org.refactor;

import org.refactor.ModelEditorStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelEditorStandaloneSetup extends ModelEditorStandaloneSetupGenerated {
  public static void doSetup() {
    ModelEditorStandaloneSetup _modelEditorStandaloneSetup = new ModelEditorStandaloneSetup();
    _modelEditorStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
