/**
 * generated by Xtext 2.10.0
 */
package org.refactor;

import org.refactor.AbstractModelEditorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelEditorRuntimeModule extends AbstractModelEditorRuntimeModule {
}
