/*
 * generated by Xtext 2.10.0
 */
package org.refactor.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.refactor.parser.antlr.internal.InternalModelEditorParser;

public class ModelEditorTokenSource extends AbstractIndentationTokenSource {

	public ModelEditorTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalModelEditorParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalModelEditorParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalModelEditorParser.RULE_END;
	}

}
